version: '3.8'

services:

  soc:
    build: .
    ports:
      - "6000:6000"
    restart: always      
    volumes:
      - ./logs:/app/logs
      - ./sqlite_db:/app/sqlite_db
    networks:
      - daa-kafka-cluster-network
    environment:
      - KAFKA_BROKER=daa-kafka1:19092
      - ZOOKEEPER_CONNECT=daa-zoo1:2888
      - TZ=Asia/Seoul
    command: python soc_250429pine.py

  mobile:
    build: .
    ports:
      - "31910:31910"    
    volumes:
      - ./logs:/app/logs
      - ./sqlite_db:/app/sqlite_db
    restart: always      
    networks:
      - daa-kafka-cluster-network      
    environment:
      - KAFKA_BROKER=daa-kafka1:19092
      - ZOOKEEPER_CONNECT=daa-zoo1:2888
      - TZ=Asia/Seoul      
    command: python mobile.py

  nodemqtt:
    build: .
    volumes:
      - ./logs:/app/logs
      - ./sqlite_db:/app/sqlite_db
    restart: always
    networks:
      - daa-kafka-cluster-network      
    environment:
      - KAFKA_BROKER=daa-kafka1:19092
      - ZOOKEEPER_CONNECT=daa-zoo1:2888
      - TZ=Asia/Seoul      
    command: python nodemqtt_2.py

  vehicle:
    build: .
    volumes:
      - ./logs:/app/logs
      - ./sqlite_db:/app/sqlite_db
    restart: always
    networks:
      - daa-kafka-cluster-network      
    environment:
      - KAFKA_BROKER=daa-kafka1:19092
      - ZOOKEEPER_CONNECT=daa-zoo1:2888
      - TZ=Asia/Seoul
    command: python vehicle.py 

  vehicle:
    build: .
    volumes:
      - ./logs:/app/logs
      - ./sqlite_db:/app/sqlite_db
    restart: always
    networks:
      - daa-kafka-cluster-network      
    environment:
      - KAFKA_BROKER=daa-kafka1:19092
      - ZOOKEEPER_CONNECT=daa-zoo1:2888
      - TZ=Asia/Seoul
    command: python vehicle_list.py 

  vehi:
    build: .
    volumes:
      - ./logs:/app/logs
      - ./sqlite_db:/app/sqlite_db
    restart: always
    networks:
      - daa-kafka-cluster-network      
    environment:
      - KAFKA_BROKER=daa-kafka1:19092
      - ZOOKEEPER_CONNECT=daa-zoo1:2888
      - TZ=Asia/Seoul
    command: python vehi.py 
    
  stsw:
    build: .
    volumes:
      - ./logs:/app/logs
      - ./sqlite_db:/app/sqlite_db
    restart: always
    networks:
      - daa-kafka-cluster-network      
    environment:
      - KAFKA_BROKER=daa-kafka1:19092
      - ZOOKEEPER_CONNECT=daa-zoo1:2888
      - TZ=Asia/Seoul      
    command: python stsw.py

networks:
  daa-kafka-cluster-network:
    driver: bridge